### ISSUE TITLE
Animation support

### ISSUE THREAD

**Issue by AdrianCarmonaRoda** [GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon#118]
Hello!
I just installed the hydra pluging for Blender, my goal is to animate in Maya but render in Blender.
The problem is that I can't get the Animation of the .usd file working on hydra.
Is animation not supported?

**Comment by bnagirniak** [comment]
Hello, animation of .usd is not yet supported, it'll be done in nearest future.

**Comment by bnagirniak** [comment]
We've already made initial support of animated USD files in #168

**Comment by VascoPi** [comment]
There is an initial support only for viewport render.

**Comment by VascoPi** [comment]
Should be fixed in https://github.com/GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon/pull/233
