### ISSUE TITLE
Buil against a USD library

### ISSUE THREAD

**Issue by Animatect** [GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon#142]
Hi, I wold love to use blender to develop an artist friendly Karma ( houdini ) pipeline, I was wandering, is it possible and what would be the best way to build the plugin against the Houdini USD library, instead of trying to build karma against the plugin's own USD libraries, since building Karma is a whole ordeal.

The idea would be to have artists using Blender to develop assets in Karma using USD and Material X, bypasing this way the costs attached to  getting artist up to speed with houdini and the cost of a Core license which would be heavily under used, then a Houdini artist can do the assembly of the scene and send to render using Solaris.

**Comment by bnagirniak** [comment]
Please look here https://github.com/GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon/blob/master/tools/build_usd.py#L57
Here are the parameters which we provide to build_scripts/build_usd.py script for USD build. You can add there additional parameters for your needs and run our build script (see https://github.com/GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon/blob/master/README.md#build-tool):
`python tools/build.py -all -bin-dir <bin folder>`

**Comment by Animatect** [comment]
Thank you :)
