### ISSUE TITLE
Linux and Mac requirements

### ISSUE THREAD

**Issue by melMass** [GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon#16]
Hi,

First and foremost thanks a lot for this.

Can you please provide a deeper explanation on why other platforms support is not available yet?

I have the same issue with most of the recently released projects from this AMD initiative (https://github.com/GPUOpen-Effects/FEMFX/issues/1 for instance), some support Linux only other Windows only, but the reasons aren't clear and I think stating them clearly will help others to contribute or find workarounds?

Thanks

**Comment by bsavery** [comment]
Hi there!  And thanks for the interest.  

Linux:  Should work fine, we just haven't compiled a release for linux yet.  
macOS:  There's actually a blender bug here:  https://developer.blender.org/T76490

Most of this code is python so should be cross compatible, I can't speak to the other project which I'm not involved in.  Also I'd note this is now meant for more developers than users at the moment!  Thanks

**Comment by melMass** [comment]
Great news for Linux.
Oh yes, dynamic libraries on macOS is a real pain...
I did not realize the implementation was python-based!
Thanks for the reply. I'm testing it now!

**Comment by bsavery** [comment]
Well, on macOS they actually statically link USD into Blender, so this addon clashes with that.  We're talking with Blender how to address this!
