### ISSUE TITLE
Visual Studio embedded python interpreter

### ISSUE THREAD

**Issue by smeunier-amd** [GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon#164]
Installing Visual Studio embedded python interpreter (3.7) leads to various building problems (MaterialX python bindings...).

Once uninstalled I was able to build the addon at commit [379428d6837](https://github.com/GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon/commit/379428d68378e543ee6a901608f8dbe7fd839aab) with no problem.

**Comment by bnagirniak** [comment]
Thank you for reporting this issue, we'll fix this.

**Comment by bnagirniak** [comment]
It should be fixed in #176
