### ISSUE TITLE
Failed rendering AnimalLogic USD Lab

### ISSUE THREAD

**Issue by IRONIC3D** [GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon#179]
Loading the [AnimalLogic USD Lab](https://animallogic.com/usd-alab/) results in a single collection with no objects to manipulate, also the scene is flipped -90 degrees and cannot be rotated or moved to a custom position.

**Comment by DagerD** [comment]
Hi. Thanks, we will take a closer look at this scene.

**Comment by bnagirniak** [comment]
@IRONIC3D can you please try to use Transform node to rotate the scene in USD nodetree?

**Comment by IRONIC3D** [comment]
Hi @bnagirniak , opening the USD node is crashing Blender for me. I've updated to 2.93.7 since last reported it. Updating to 2.93.8 today to see if that solves the crash.

The crash is not happening to other scenes.
