### ISSUE TITLE
Kitchen Scene Instances loads incorrectly

### ISSUE THREAD

**Issue by IRONIC3D** [GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon#180]
The instance version of the Kitchen scene renders incorrectly
![image](https://user-images.githubusercontent.com/300186/147023857-0b12382d-7cb0-4ca8-8f94-4e7cfcc0fb37.png)

**Comment by bnagirniak** [comment]
Please, send us blender scene with USD node tree.

**Comment by DagerD** [comment]
Should be fixed soon with update of HdRPR.

**Comment by DagerD** [comment]
@IRONIC3D You can now test how it works.

**Comment by IRONIC3D** [comment]
Thanks @DagerD, I'll need to build the latest changes to test. I'll keep you posted once that is done.

**Comment by ARozghon** [comment]
![image](https://user-images.githubusercontent.com/68949117/152023289-08aa0aab-7173-4d54-a669-8eb797872484.png)
fixed with the latest master
