### ISSUE TITLE
Blender 2.93 , 3.0 and 3.1 crashing

### ISSUE THREAD

**Issue by Confabulatori** [GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon#181]
Hi, I'm new here and I don't know if is this the right place to ask and how.
Blender 2.93, 3 and 3.1, are crashing when I try to use MaterialX.

**This is the terminal.**
AttributeError: 'NoneType' object has no attribute 'hdusd'
location: <unknown location>:-1
2021-12-23 01:21:28,217 WARNING hdusd.bl_nodes [140129335244352]:  Ignoring unsupported node ShaderNodeTexChecker, <bpy_struct, ShaderNodeTexChecker("Checker Texture") at 0x7f727a5a8e08>, <bpy_struct, Material("Floor") at 0x7f727a132788>
Writing: /tmp/blender.crash.txt
Violación de segmento (`core' generado)

**The Blender crash file**
[blender.crash.txt](https://github.com/GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon/files/7767555/blender.crash.txt)
 backtrace
/home/carlos/Escritorio/Blender/blender(BLI_system_backtrace+0x20) [0xb198d40]
/home/carlos/Escritorio/Blender/blender() [0x10f721a]
/usr/lib/libc.so.6(+0x3cda0) [0x7efc31412da0]

 Python backtrace
  File "/home/carlos/.config/blender/3.1/scripts/addons/hdusd/engine/preview_engine.py", line 98 in render
  File "/home/carlos/.config/blender/3.1/scripts/addons/hdusd/engine/engine.py", line 85 in render

**And my specs**
Operating System: EndeavourOS
KDE Plasma Version: 5.23.4
KDE Frameworks Version: 5.89.0
Qt Version: 5.15.2
Kernel Version: 5.15.10-arch1-1 (64-bit)
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 5600X 6-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3070/PCIe/SSE2
Thank you.

**Comment by Confabulatori** [comment]
Also crashes when I change the viewer mode to rendered view
[blender.crash.txt](https://github.com/GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon/files/7771837/blender.crash.txt)

**Comment by DagerD** [comment]
Hi. Can you please attach scene?

**Comment by ARozghon** [comment]
https://github.com/GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon/tree/master/src/hdusd pls, try to reproduce with this version of USD hydra

**Comment by bsavery** [comment]
I also uploaded a new build which may fix linux issue.

**Comment by Confabulatori** [comment]
@DagerD Thank you for answer. I forgot to say is a clean scene just a plane or a cube, I used only one object to try it

**Comment by Confabulatori** [comment]
@ARozghon, @bsavery, Thank you. 
I'll try it.

**Comment by Confabulatori** [comment]
@ARozghon I tried to build it (.66 version) but I know very little about how to do it, when I build the addon (build.py -addon) the addon was incomplete (pxr module not found), then I supposed that I needed to build.py -all, to make it work, but CMake couldn't find pybind11tools, then I installed pybind11 but CMake still doesn't find it, so I copied the missing files (lib) from the build version .65 of the addon to the new one (.66) and it worked, now Blender accepted the addon and doesn't crashes when I'am in the materials tab, I can browse and download and press the import button but it doesn't create the nodes, is an empty material, . Blender 3.1 Crashes when I change the viewport shading to rendered, only with RPR, I suppose due the lack of OpenCl support in Cycles X, Blender 2.93 doesn't have this problem but also crashes with the materials and also there aren't nodes with this method that I used.
@bsavery I was using the version 1.0.65 it was (and it is) the latest version build that I found. 
Thank you!
![image](https://user-images.githubusercontent.com/96521641/147404779-ad55d855-2a0f-48af-9576-69a4aaa8939a.png)

**Comment by DagerD** [comment]
If you want to build addon by yourself, the correct command line is (from root): `python tools/build.py -all -bin-dir <bin folder>`

Also don't forget to install all necessary dependencies for python before building ([see readme](https://github.com/GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon#build-requirements)).

Also you can try to install addon from latest release to test what you want https://github.com/GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon/releases/tag/v1.0.65

**Comment by Confabulatori** [comment]
Thank you. 
I'll close this issue, for sure this is due my lack of knowledge, I'll keep an eye in the development to try later it in the next releases.
Thank you for your work!
