### ISSUE TITLE
Request - Linux build

### ISSUE THREAD

**Issue by statixVFX** [GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon#19]
Would love a linux build of this.

**Comment by bsavery** [comment]
Will do!

**Comment by Kaiz3rTool** [comment]
a linux release would be amazing, I see that the PR is merged, does it means that we will be able to test it on linux at the next release or do we have to compile ourself ?

**Comment by bnagirniak** [comment]
Yes, linux build is ready, it'll be available in next release.
It is also available to compile yourself, but we haven't yet updated documentation how to do that.

**Comment by Kaiz3rTool** [comment]
ok thanks, i will wait the next release then :)
bests !

**Comment by SteffenDuenner** [comment]
LInux build works! Great :)
