### ISSUE TITLE
Undo of a transform doesn't update the transform

### ISSUE THREAD

**Issue by IRONIC3D** [GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon#201]
When moving, rotating or scaling a referenced object using the gizmo or the numerical controls the object will transform. However if you undo then the gizmo control will go back to it's original/previous position but the object will stay in place. The only way to trigger the object to snap back to it's previous place is by placing the cursor in the numerical input of that channel and pressing "Enter". Only then the object will snap back to it's previous place.

**Comment by IRONIC3D** [comment]
Hi Georgiy

As shown in this video, the fridge or chair can either be moved by directly selecting them and moving the gizmo or using the transform property. Bellow are the issues:

1. With the current public release of HydraBlender the transform don't work. Meaning selecting and moving doesn't do anything. (i.e. with v2.93.8). Instead a transform node with filtering is required.
2. Building from source on the 23rd of Feb Fixes this issue. And I am able to transform any object either using the on-screen gizmo or the transform property of the object.
3. When transforming using the Gizmo or the transform property (as in the video above) the object moves. If I Undo the motion, then the Gizmo jumps into it's previous place (as it should be) however, the geometry is not updated and stays in position.
4. To properly undo a transform (e.g. translation, rotation or scale) I'll need to bring up the transform property of the object, select any field|axis and press enter. This will trigger a refresh(?) and the geometry snaps back into it's original place, thus matching the gizmo.

I hope the is clear?

Thank you

**Comment by DagerD** [comment]
Got it, thank you.

Confirmed as BLEN-56.
