### ISSUE TITLE
Blender hangs with Lego 856 Bulldozer scene

### ISSUE THREAD

**Issue by pablode** [GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon#207]
Tested with latest master (1.0.77) and Blender 3.0.1.

To reproduce:
1. open Lego 856 Bulldozer scene: https://blendswap.com/blend/11490
2. set Render Engine to 'USD Hydra'
3. observe Blender hanging indefinitely

The following message is emitted periodically:
```
Dependency cycle detected:
  OBArmature/Bone.018/POSE_IK_SOLVER() depends on
  OBArmature/Bone.016/BONE_DONE() via 'IK'
  OBArmature/Bone.016/POSE_IK_SOLVER() via 'IK Solver Result'
  OBArmature/Bone.018/BONE_DONE() via 'IK'
  OBArmature/Bone.018/POSE_IK_SOLVER() via 'IK Solver Result'
Detected 1 dependency cycles
```

**Comment by DagerD** [comment]
Hi.

Actually it works but requires a lot of time. Also, if you disable one viewport, render will finish mush faster.

**Comment by pablode** [comment]
Yes, you're right, thank you!
