### ISSUE TITLE
Addon is not initialized properly

### ISSUE THREAD

**Issue by kalemas** [GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon#213]
Hello, i had checked whatever i can, but cant get Addon work for me. 

I expected to have NodeTree option, but it is lost 
![image](https://user-images.githubusercontent.com/638393/157031234-db827835-d255-4297-9be6-4489a3702462.png)

i have no usd nodes as well.

blender: `>>> bpy.app.version (2, 93, 8)` system: `>>> platform.uname()
uname_result(system='Windows', node='ws111', release='10', version='10.0.19041', machine='AMD64')`

I did n't had any error when installing Addon and restarted before final testing.

**Comment by DagerD** [comment]
Hi.

To see NodeTree option you need to create one:
![image](https://user-images.githubusercontent.com/42409851/157427486-2f226a06-9b5a-4f2a-bc60-b3ad99203407.png)

**Comment by kalemas** [comment]
Sorry, i have no such view :^S
![IMG_20220309_204220](https://user-images.githubusercontent.com/638393/157499812-5ae3ebf0-05b0-41b7-8a6d-08e6ab9f3dab.jpg)

**Comment by DagerD** [comment]
It might be not visible if you didn't choose USD Hydra as render engine.

**Comment by kalemas** [comment]
Got it working, thank you! I think i have to PR to update a readme.
