### ISSUE TITLE
not responding in Blender 3.12&3.2

### ISSUE THREAD

**Issue by 1405100494** [GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon#250]
HI!
I try the Hyda 1.1 .But when chose to rendering mode.It always not responding.The Hyda addon last version still worked.The 1.1 is not work.I try to use deform setting but it also not responding.Is it don't supprot Ndvdia graphics cards
![Blender3 12 3 2_Hyda_1 1](https://user-images.githubusercontent.com/72635400/172551879-c394f456-61bb-4eb8-9830-27677b836f4c.png)
?

**Comment by 1405100494** [comment]
I found that it was only unresponsive in fullrender mode.It can work in interactive mode.Maybe it is a bug or something need to set up.

**Comment by 1405100494** [comment]
Does the plugin currently support bone animation？It seems that the bone animation is not exporting correctly.

**Comment by VascoPi** [comment]
Thanks for the report. Could you provide the scene you have an issue with?

**Comment by 1405100494** [comment]
Thank you for your reply! 
I try it use the 3.2 offical verision just now.It can work well.Maybe the problem is in the daily builds.
I see the BlenderUSDHydra will in next blender pepline Meeting.Nvidia also has a USD division.Although it supports more data, it is destructive.The BlenderUSDHydra is nondestructive.
Thanks to your development, next upgrade it will be more imposed！
