### ISSUE TITLE
MaterialX nodegraph available

### ISSUE THREAD

**Issue by fire** [GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon#252]
> There is a MaterialX based nodegraph available under the "MaterialX" editor.

How would I enable this? I looked for 20 minutes.

Blender 3.2

**Comment by fire** [comment]
1. Install the addon
2. Enable USD Hydra
3. Change scene render to USD Hydra
4. Go to the shading view at the top
5. Open the right menu.

![image](https://user-images.githubusercontent.com/32321/175198845-19f4be00-3f76-4e1f-83dd-9feaaa452340.png)

![image](https://user-images.githubusercontent.com/32321/175198903-7ff4aef0-f140-448a-93f5-ec290c227fdb.png)

**Comment by bsavery** [comment]
It looks like you found the MaterialX editor?

**Comment by fire** [comment]
Yes!

**Comment by fire** [comment]
To be clear. The requested next step is to update the documentation so it's easier to find.

**Comment by fire** [comment]
Thanks.
