### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by adro79** [GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon#269]
It's been months since the latest release..

I don't know if blender developers are working on an integrated hydra add-on, would be cool tho

**Comment by bsavery** [comment]
Yes, you can track the development we are assisting blender with here:  https://developer.blender.org/T100892

**Comment by adro79** [comment]
Great to know, thanks!

Would be great to have that information in the README
