### ISSUE TITLE
Blender Hydra Node Tree Doesn't Refresh With USD Changes

### ISSUE THREAD

**Issue by matiascodesal** [GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon#30]
[refresh_repro.zip](https://github.com/GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon/files/5792199/refresh_repro.zip)

I've set up a Node Tree showing that if I change the USD file input to another file or edit the referenced USD file on disk, the addon doesn't update with the changes.  The only way that I've found to force an update to delete the node tree and set it up again.

1. Extract refresh_repro.zip
2. Open blender_hydra_refresh_repro.blend
3. Change the viewport shading to "Rendered" to see a cube rendered at the origin.
4. In the node tree, change the USD file from "//cube.usda" to "//plane.usda".  The USD list does not update and no changes are noticed in the viewport.
5. You'll notice the same issue if you make any changes to cube.usda.  The changes aren't reflected.

**Comment by bnagirniak** [comment]
Yes, such USD tree updates aren't implemented yet, we'll be working on this.
