### ISSUE TITLE
Building/installing Issue

### ISSUE THREAD

**Issue by suekieza** [GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon#35]
Hey there,

Windows 10
Blender 2.91
Downloaded: BlenderUSDHydraAddon_1.0.0_Windows.release.1.zip
and the source code.zip

I've been trying to get this plugin working on my home pc. But get this error:
![blender addon issues](https://user-images.githubusercontent.com/53234220/105833285-a7072900-5fd1-11eb-9552-4a89bce910df.PNG)

My env looks like:
![envblenderaddon](https://user-images.githubusercontent.com/53234220/105833490-ecc3f180-5fd1-11eb-8dc3-0ddc4ccc71f1.PNG)

I run: run_blender_with_plugin.cmd to open Blender. Im not sure what step I'm missing...

Thanks for any help
Sue

**Comment by suekieza** [comment]
https://github.com/GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon/issues/18 looks like this is still a thing ?

**Comment by suekieza** [comment]
Ok got it working nevermind me :D

**Comment by bnagirniak** [comment]
Thanks!
