### ISSUE TITLE
How do you import USD files?

### ISSUE THREAD

**Issue by delebash** [GPUOpen-LibrariesAndSDKs/BlenderUSDHydraAddon#61]
Under File/Import there is no USD option.   Thanks.

**Comment by bnagirniak** [comment]
You can do this in USD nodetree, where you have flexibility of working with USD, like: read USD from file or from Blender scene, merge USDs, filter, etc.
Also, you have to select required USD nodetree in render settings.

**Comment by delebash** [comment]
ok thanks!
